INSERT into [Loula].FoodItem (Name, FoodTypeId)
values
(
('Spaghetti', 1),
('Gnocchi', 1),
('Potatis', 3),
('Morötter',3),
('Vitkål',6),
('Rödkål', 6),
('Grönkål', 6),
('Brysselkål', 6),
('Svartkål', 6),
('Gul lök', 4),
('Vitlök', 4),
('Rödlök', 4),
('Purjolök', 4),
('Gräslök', 4),
('Salladslök', 4),
('Pak Choi', 8),
('Mangold', 8),
('Spenat', 8),
('Isbergssallad', 8),
('Sallad', 8),
('Romansallad', 8),
('Ruccola', 8),
('Wasabiruccola', 8),
('Rödbeta', 3),
('Gulbeta', 3),
('Kålrot', 3),
('Kålrabbi', 3),
('Majrova', 3),
('Polkabeta', 3),
('Sötpotatis', 3),
('Banan', 5),
('Äpple', 5),
('Päron', 5),
('Melon', 5),
('Honungsmelon', 5),
('Vattenmelon', 5),
('Cantaloupe', 5),
('Galia', 5),
('Surkål', 6),
('Gurka', 2),
('Tomater', 2),
('Paprika', 2),
('Fänkål', 2),
('Spetskål', 6),
('Stjälkselleri', 6),
('Selleri', 6),
('Sharonfrukt', 5),
('Persimon', 5),
('Apelsin', 5),
('Mandarin', 5),
('Nektarin', 5),
('Satsumas', 5),
('Clementin', 5),
('Kyckling', 7),
('Nötfärs', 7),
('Fläskfärs', 7),
('Blandfärs', 7),
('Matlagningsgrädde', 8),
('Creme Fraîche', 8),
('Smör', 8),
('Rapsolja', 11),
('Olivolja', 11),
('Falukorv', 7),
('Choritzo', 7),
('Fläskfilé', 7),
('Oxfilé', 7),
('Entrecote', 7),
('Lövbiff', 7),
('Ägg', 10),
('Halloumi',  8),
('Riven ost',  8),
('Parmesan', 8)
)